Rewrite Extent & Domain Inference
spcl/spada pull request #10
Opened 2024-08-23 10:05 UTC by luxfg

I rewrote the extent & domain inference so that extents & domain accesses are "local" in scope.

That is, a type annotation on a statement means that the statement accesses a certain sub-domain of the field with offsets as described. To see the size of a field, one should look at the domain of the computation arguments or program arguments. These in turn do not carry meaningful offset information, hence we leave it un-inferred.
Because types are "local", we do not need the "in interval" notation for types anymore: Each computation has its own types that are bound to its scope.

The main workhorse of the analysis is a "Def-Use" analysis. Then, we work backwards through the program using a reversed-visitor, to which I add scoping information using a stack of scopes. This allows us to make the inferences using the general paradigm:

- Initialize outputs based on previous knowledge, if there are no uses.
- Consider all the in-scope uses of an output, and combine the information to deduce the result type.
- Recurse into the constuct, if necessary
- Construct input type based on local information and the result type

Note that the order of these steps and the specifics vary from op to op and analysis to analysis.

To make this work, we require proper return statements at the end of every computation and program. I have added them in most of the examples, but not yet updated the lowering from gt4py (probably faster if you do it).

With this new interpretation, we should be well equipped for lowering to spatial (or any other ir) because we have all the info to construct compute ranges (from statement types) and place ranges (from computation types & statement output types) and more. 

There are still some cornercases that I want to test more thoroughly, but most of the functionality works,  without materialize, with mutliple returns, and if-else constructs. The extent inference works with and without materialize, but I am still working on making domain inference work without materialize.

I also made some minor changes to the IR, mainly addressing some idiosyncrasies.

2024-08-23 10:12 UTC, luxfg commented
Note that we require all computations and programs to end with a return statement, so the gt4py lowering fails. @tbennun could you implement that change?

Adding returns makes all the analysis passes a lot nicer, because the returns make the use explicit.

2024-08-23 22:55 UTC, tbennun requested changes
Overall good changes, but domain inference seems to still have a bug with non-materialized codes and we should discuss some aspects of the SSA definition w.r.t. scope isolation.

2024-08-23 22:55 UTC, tbennun commented on samples/spst/if_else.spst
> +      spst.return %qstar#2 : field<[?,?,?], {(?, ?, ?)}, f32>
There is a bit of an issue here with the version being incremented in a branch. Let's discuss.

2024-08-23 22:55 UTC, tbennun commented on samples/spst/laplacian_mat_ext_dom.spst
> +                : spst.field<spst.cartesian<-1:129,-1:130,0:80>,
There is a bit of a discrepancy with this one and how domain inference works (see `no_mat_ext_dom` version). When I read this it seems like it should only go to 130.

2024-08-23 22:55 UTC, tbennun commented on samples/spst/laplacian_no_mat_ext_dom.spst
> +                : field<[-1:129,-1:131, 0:80], {(0, 0, 0), (-1, 0, 0), (1, 0, 0), (0, -1, 0), (0, 1, 0), (0, 1, 0), (-1, 1, 0), (1, 1, 0), (0, 2, 0)}, f32>
Looks like this should be -1:130, but the test fails if this is not 131. I think this is incorrect and the code should be fixed so that it's -1:130

2024-08-23 22:55 UTC, tbennun commented on samples/spst/laplacian_no_mat_ext_dom.spst
> +       field<[-1:129, -1:131, 0:80], {(?, ?, ?)}, f32>
See below

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/lowering/gt4py_to_stencil_ir.py
> +                    pass
I don't know whether we should increment the versions in the body of each if/elseif. Let's discuss. If we do increment the versions, this becomes a recursive traversal of the body and else(if) bodies.

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +    This assumes that the program is in SSA form, that is, each identifier is defined exactly once.
So, in MLIR there is the notion of IsolatedFromAbove scopes. We may want to reuse these kinds of scopes here. Otherwise looks good.

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        :param def_use: If None, the def-use analysis is disabled.
```suggestion

        :param def_use: If None, the def-use analysis is disabled.
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        :return:
```suggestion
        Adds a use of a field to the def_use dictionary, with the current scope.

        :param node: The identifier
        :param field_type: The field type object
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        :return:
Notice how there must be an empty newline between the definition and param for Sphinx/readthedocs to work

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        :return:
```suggestion
        Adds a definition of a field to the use_def dictionary, with the current scope.

        :param node: The identifier
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        :return:
```suggestion
        A statement uses all its argument types and defines all its outputs.

        :param node: The node to visit.
```
Also this is more of a comment rather than a method documentation IMO.

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        """
```suggestion
        """
        A materialize operation uses its argument and defines its output.

        :param node: The node to visit.
        """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        """
```suggestion
        """
        An if block uses its condition and the conditions of its if-else blocks.
        The if-else blocks share the same type as the if block.
        An if block defines its outputs.

        :param node:  The node to visit.
        """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        """
```suggestion
        """
        A computation block uses all its inputs and defines all its outputs.

        :param node: The node to visit.
        """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        """
```suggestion
        """
        Within the computation block, all inputs are defined.

        :param node: The node to visit.
        """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +        # A return uses all its arguments and does not define anything
I would convert all prior docstrings to comments like this.

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +                arg_t = node.operation_type.source[i]
Why is this here if someone else fills the operation type before domain inference? Where does it fail if you remove this?

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/lark_to_ast.py
> +        assert False, "NOT SUPPORTED"
Please `raise NotImplementedError` instead (standard Python)

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/lark_to_ast.py
> +    return tuple((dim for dim in tup))
```suggestion
    return tuple(tup)
```
Also this function is obviated now

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/lark_to_ast.py
> +        optype = next((i for i in range(len(args)) if isinstance(args[i], irnodes.OperationType)), None)
Why not check for the last argument? Shouldn't a args always take the type of [value1, ..., valueN, (OperationType)?]

2024-08-23 22:55 UTC, tbennun commented on tests/test_type_inference.py
> +                        if isinstance(statement, StatementBlock) or isinstance(statement, MaterializeOp):
```suggestion
                        if isinstance(statement, (StatementBlock, MaterializeOp)):
```

2024-08-23 22:55 UTC, tbennun commented on tests/test_type_inference.py
> +                    if isinstance(statement, StatementBlock) or isinstance(statement, MaterializeOp):
```suggestion
                    if isinstance(statement, (StatementBlock, MaterializeOp)):
```

2024-08-23 22:55 UTC, tbennun commented on tests/test_type_inference.py
> +        """
```suggestion
        """
        Asserts that all domains have been inferred. Raises assertion exceptions on failure.

        :param program: The program to test.
        """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/extent_inference.py
> +        self.extents[node.value.name].add(sast.Offset((node.subscript[0], node.subscript[1], node.subscript[2])))
```suggestion
        self.extents[node.value.name].add(sast.Offset((node.subscript[0], node.subscript[1], node.subscript[2])))

```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/extent_inference.py
> +        self.extents[node.value.name].add(sast.Offset((node.subscript[0], node.subscript[1], node.subscript[2])))
Add newline to end of file

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/domain_inference.py
> +    # TODO Adapt for non-zero offsets
Is this TODO not resolved? Also, why is it in the docstring? (additionally, please fix the docstring's formatting, i.e., document return value and add newline)

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/extent_inference.py
> +        """
```suggestion
        """
        Get the offsets of the uses of a field in the current scope.

        :param computation: The current computation block
        :param identifier: The identifier
        :return: A list of offsets
        """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/extent_inference.py
> +    """
```suggestion
    """
    Initialize the extents of every element to be (0, 0, 0)

    :param dtypes: Field type elements to set.
    """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/extent_inference.py
> +    """
```suggestion
    """
    Compute the Minkowski sum of two sets of extents.

    :param a: First set operand.
    :param b: Second set operand.
    :return: The Minkowski sum set result.
    """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/extent_inference.py
> +        assert all(not o.is_unknown() for o in offsets), f"Offsets of uses of {identifier.name} must be known before inference"
Don't you want to move the assertion before the filtering? Also, when does this happen?

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/extent_inference.py
> +    """
```suggestion
    :param program: The program whose extents should be inferred (operates in-place).
    """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/domain_inference.py
> +    """
```suggestion
    """
    Get the offsets of the uses of a field in the current scope.

    :param uses: The uses dictionary
    :param computation: The current computation block
    :param identifier: The identifier
    :return: A list of offsets
    """
```

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    # TODO: Why do math calls not have types?!
A math call is not an operation, so it does not have a type. Their type is inferred as part of the operation they partake in.
It would be the same as asking "why does a unary operator IR node not have a type".

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
>      """
An else-if block is always nested in an IfBlock, which does have one. It is important to fix the IfBlock (which is the Operation here) type and the other blocks to have the same operation type.
Notice that ElseIfBlock is _not_ an Operation in and of itself.

2024-08-23 22:55 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +        :return:
Please fix docstring formatting (newline before parameter, and if there is no documentation for the params or return value, they should be removed).

2024-08-26 08:34 UTC, luxfg commented on samples/spst/laplacian_no_mat_ext_dom.spst
> +                : field<[-1:129,-1:131, 0:80], {(0, 0, 0), (-1, 0, 0), (1, 0, 0), (0, -1, 0), (0, 1, 0), (0, 1, 0), (-1, 1, 0), (1, 1, 0), (0, 2, 0)}, f32>
No, the test is failing on purpose. The important thing is that we should define it so that the input field %in has the same size regardless of if you materialize or not. Moreover, one needs to interpret a temporary field with more than one extent as having at each coordinate not just its own gridpoint value, but that of all extents. Let's walk through the example (it's easier to verify bottom up).


```
        // We need to compute for each gridpoint in [0:128, 0:128, 0:80] its value and the value of its 0,1,0 neighbor. For the first, we need %in domain [-1:129, -1:129, 0:80], for the second %in domain [-1:129, 0:130, 0:80]. The result is the union of the two domains.
        %out_1 = spst.statement(%in)
                : field<[-1:129,-1:130,0:80], {(0, 0, 0), (-1, 0, 0), (1, 0, 0), (0, -1, 0), (0, 1, 0), (0, 1, 0), (-1, 1, 0), (1, 1, 0), (0, 2, 0)}, f32>
                -> field<[0:128, 0:128, 0:80], {(0, 0, 0), (0, 1, 0)}, f32>
            {
                return -4.0 * %in[0, 0, 0] + %in[-1, 0, 0] + %in[1, 0, 0] + %in[0, -1, 0] + %in[0, 1, 0]
            }
         // Since we have for each gridpoint in %out_1 its value and the value of 0,1,0, and no other values are needed for the 0,0,0 offset, the domain size of %out_1 matches that of %out_2
        %out_2 = spst.statement(%out_1)
                : field<[0:128, 0:128, 0:80], {(0, 0, 0), (0, 1, 0)}, f32>
                -> field<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>
            {
                return %out_1[0, 0, 0] + %out_1[0, 1, 0]
            }
         // The output size is given
        return %out_2 : field<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>
```

2024-08-26 08:35 UTC, luxfg commented on spatialstencil/lowering/gt4py_to_stencil_ir.py
> +                    pass
I mean the cleanest is to have a pass on the stencil ir that transforms any program into SSA.

2024-08-26 08:37 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    # TODO: Why do math calls not have types?!
Yes, makes sense.

2024-08-26 08:38 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
>      """
Yes, makes sense.

2024-08-26 08:38 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +        :return:
sure

2024-08-26 08:44 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +                arg_t = node.operation_type.source[i]
Yes, this should be done elsewhere.It fails if you don't explicitly annotate all the return types as field types (the hdiff, uvbke, vadv, hdiffsa examples don't annotate returns yet for example). We should have a pass that fills in 'any' types with either scalar or field types depending on the context.

2024-08-26 08:47 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/lark_to_ast.py
> +        optype = next((i for i in range(len(args)) if isinstance(args[i], irnodes.OperationType)), None)
Arguments can have different types. For example. you can have computation that returns an f32 fields and an f16 field. Moreover, some fields could be "2D" while others are "3D". So you cannot rely on the last value only.

2024-08-26 09:14 UTC, luxfg commented on spatialstencil/lowering/gt4py_to_stencil_ir.py
> +                    pass
I think we should have new versions in the if-else to ensure it's strictly SSA. It simplifies the use-def / def-use analysis.

2024-08-26 09:20 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +    This assumes that the program is in SSA form, that is, each identifier is defined exactly once.
Yeah in principle, computations and statements (and programs) are indeed 'isolated from above' scopes. We are not using or checking that here.

2024-08-26 09:22 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +    This assumes that the program is in SSA form, that is, each identifier is defined exactly once.
It might be nice to actually check the isolation of scopes.

2024-08-26 16:23 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/def_use_analysis.py
> +    This assumes that the program is in SSA form, that is, each identifier is defined exactly once.
I understand now what you meant. As discussed, we will only enforce new versions within the isolatedFromAbove scopes.

2024-08-27 11:31 UTC, luxfg commented
Ok, I had another look at some vertical stencil examples and writing to input arrays, and thought about the view vs field concepts. Here is my current understanding:

---

fields vs views:

- computations should operate on views, because when we have intervals they access only part of the field. In terms of lowering to spatial, the views of arguments should convey the bounds of the computation. The vertical stencil example (vertical_intervals_ext_dom.spst) clarifies this idea.
- programs should operate on fields.

I realize that the computations still have ? argument extent types, which is a bit awkward, but conceptually they have to be views I think. If we wanted to be super clear, we could have a subtype of views that do not have extents and are exclusively used for compute arguments. The benefit of this is marginal I think though.

What do you think?

Can you adjust the lowering to create FieldType / ViewType appropriately?

----

Writing to computation arguments:

- when we write to an input array view, we should return the view that we overwrite and assign it to the corresponding field. This is the cleanest way to ensure proper def-use chains without creating cycles and is the clearest semantically.
- Using arguments as silently being used by statement that write to them creates cycles in the analysis, which is problematic and would require an iterative method I think. Using explicit returns keeps the analysis 1 pass. Hence, I strongly encourage to use the return approach.

I have made an example  (vertical_readwrite[_ext_dom].spst) to demonstrate this interpretation. 

Does that make sense?

If you agree and we don't find any important cases this does not cover, can you adjust the codegen to generate proper returns?

2024-09-09 13:49 UTC, luxfg commented
I adjusted the lowering to use fields in the program arguments and fixed the SSA versioning for nested if-else, by implementing a proper SSA pass in the stencil IR. The only remaining issue is the proper creation of inputs/outputs. The cleanest solution would be to use the Def-Use / Use-Def chains, but it might also be possible to extend the current input/output visitor.

2024-09-09 14:26 UTC, luxfg commented
I adjusted the output pruning to keep outputs that are used as arguments to SOME computation. This is a conservative way to ensure that we do not remove fields that are over-written.

2024-09-10 04:59 UTC, tbennun approved these changes
Just a little bit of cleanup, otherwise looks good!

2024-09-10 04:59 UTC, tbennun commented on tests/test_lowering_gt4py_to_stencil_ir.py
> +        print(irprogram.as_ir())
```suggestion
```

2024-09-10 04:59 UTC, tbennun commented on tests/test_lowering_gt4py_to_stencil_ir.py
> +
```suggestion
```

2024-09-10 04:59 UTC, tbennun commented on tests/test_lowering_gt4py_to_stencil_ir.py
> +        print(irprogram.as_ir())
```suggestion
```

2024-09-10 04:59 UTC, tbennun commented on tests/test_stencil_ir_passes.py
> +            #Path(__file__).parent / Path('../samples/spst/vadv_3.spst'),
```suggestion
```

2024-09-10 11:15 UTC, merged