Spatial IR Syntax Implementation
spcl/spada pull request #11
Opened 2024-09-19 11:46 UTC by luxfg

Changes to syntax/spatial

* Draft of the Spatial IR Syntax Implementation. 

Note that it is a fairly direct translation of the syntax and does not include any control flow graph notions (yet).

Changes to syntax/common

* Refactor the scalar types into common, so we can reuse them between IRs.
* validate() should be part of the base node.
* I fixed validate_schema to work properly with UnionTypes using Union or | syntax.
* validate_schema is a class method.

Changes in syntax/stencil

* call validate_schema in the Program validate()

2024-09-22 18:20 UTC, tbennun requested changes
Looks good, very minor changes requested

2024-09-22 18:20 UTC, tbennun commented on spatialstencil/syntax/common/basenode.py
> +    def validate_schema(cls, visited: set[type['BaseNode']] = None) -> bool:
does it return true, false, and raise exceptions? I'd go with one or the other (also see/update docstring below as necessary)

2024-09-22 18:20 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +        if self.step:
```suggestion
        if self.step is not None:
```
if self.step were set to 0 directly it would not enter the condition

2024-09-22 18:20 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +        return f"{indent_str}hops = {hops_str}, \n{indent_str}channel = {channel_str}"
```suggestion
        return f"{indent_str}hops = {hops_str},\n{indent_str}channel = {channel_str}"
```

2024-09-22 18:20 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +                assert abs(dx) + abs(dy) == 1, "Each hop must have an absolute sum of 1."
nice semantics validation

2024-09-22 18:20 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +        assert self.validate_schema()
is this necessary inside node validation? normally the schema is validated separately.

2024-09-22 18:20 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +        assert self.validate_schema()
Same question here. Perhaps validate_schema on each of the IRs should be a test (part of CI)

2024-09-23 10:33 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +        assert self.validate_schema()
Yes, I think you are right.

2024-09-23 14:34 UTC, tbennun approved these changes

2024-09-23 14:34 UTC, tbennun commented on tests/test_spatial_ir_schema.py
> +class TestStencilIR(unittest.TestCase):
```suggestion
class TestSpatialIR(unittest.TestCase):
```

2024-09-23 14:36 UTC, merged