Spatial IR Harmonization and Parser
spcl/spada pull request #13
Opened 2024-09-27 18:50 UTC by tbennun

Adds a Lark/AST parser for Spatial IR. Also makes the following modifications to the standard in order to harmonize the representation:

- [x] Blocks define completion or await, fail when neither exist
- [x] Assignment of a completion object is disallowed
- [x] Typed identifiers become part of the block
- [x] `foreach` accepts generators that are implicitly zipped together. `receive(x)` is the only built-in generator and is required
- [x] `receive(arr, stream)` is a built-in function that can be used as a shorthand for `foreach i32 i, var x in [0:N], receive(stream) { arr[i] = x; }`
- [x] Parametric place/dataflow/compute block indices also have a data type

2024-10-03 08:44 UTC, luxfg requested changes
Nice overall. I am not sure what the DefinitionStatement is doing.

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +    receive_stream: Identifier
Why not use the receiveGenerator here?

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +class DefinitionStatement(Statement):
Is it an assignment or a definition?

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +        assert all(isinstance(dim, (int, Expression)) for dim in self.shape)
Ok. We should probably add a check that the Expression is compile-time known.

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +    dtype: ScalarType
Why is the type a scalar?

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +class DefinitionStatement(Statement):
I am not sure where this is used. It's not possible to define a field in a statement. It has to happen in a field declaration within the dataflow block. and for assignments, use the AssignmentStatement.

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/language.lark
> +definition : builtin_type identifier "=" value_expr
you cannot define an array or other field in a statement.

statements like

T[80] a = ...
f32 a = 5

in the compute block are not allowed.
all data must be declared in the place block using a field declarations.

am I missing sth?

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +        assert all(isinstance(dim, (int, Expression)) for dim in self.shape)
(not in this PR though)

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +    name: str
Consider having

dtype: ...
identifier: Identifier

as a signature.

2024-10-03 08:44 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +    name: str
this allows tracking identifiers regardless of if they are typed or not.

2024-10-03 13:56 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +    dtype: ScalarType
Based on the types stream can accept, they are a scalar type:
A `stream<completion>` cannot exist, nor can a `stream<f32[N]>`

2024-10-03 13:57 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +        assert all(isinstance(dim, (int, Expression)) for dim in self.shape)
True, this is checked in lowering to CSL (actually, it cannot be parametric there either).

2024-10-03 13:59 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +    receive_stream: Identifier
I was trying to keep things simpler, but we can use the generator instead. Will fix

2024-10-03 17:41 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/language.lark
> +definition : builtin_type identifier "=" value_expr
you're right. Will fix. This also removes the `DefinitionStatement` above.

2024-10-03 17:41 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +    name: str
Correct, will fix!

2024-10-04 07:50 UTC, luxfg commented on spatialstencil/syntax/spatial_ir/irnodes.py
> +    dtype: ScalarType
The StreamType is defined such that it can only hold scalar elements, so your example cannot occur in either case.

```
class StreamType(SpatialNode, IRType):
    """
    A stream type that sends elements of type T.
    """
    element_type: ScalarType
```

My interpretation is that the stream declaration creates an object that is a stream, which is why its dtype should be StreamType. Yes, the stream type holds a scalar, and it is accessible through the element_type of the stream.

2024-10-04 08:21 UTC, luxfg approved these changes
Ok. I changed the type of stream declaration as per my reasoning in the comment. I added type validations to every irnode and fixed some small issues in the type annotations and lark_to_ir.

2024-10-04 08:24 UTC, merged