Lower Stencil IR to Spatial IR
spcl/spada pull request #15
Opened 2024-09-30 13:52 UTC by luxfg

Contains:

(1) A tree pattern matching infrastructure for matching expressions

(2) Lowering of basic stencil IR, including
* Placement of memory using the 'naive' placement
* Creation of dataflow streams
* Horizontal stencil compute lowering assuming a three-address-code "canonical" form. This makes use of (1) to match expressions in the statements.

(3) Splitting and merging of blocks to ensure every pair of blocks either has the same subgrid or their subgrids do not overlap.

(4) Canonicalization (3 address code-like) of expressions in stencil IR. This uses the infra from (1).

Several operations are not yet supported including:
- ternary operations
- ifelse
- vertical stencils

I suggest to add them in another PR, as this PR contains the pattern matching infra that we should merge before doing the lowering from spatial.

Input
```
%pres = spst.program(%in) {} : spst.field<[-1:129, -1:130, 0:80], f32> -> spst.field<[0:128, 0:128, 0:80], f32> {
  %res = spst.computation (%in) {
   schedule = PARALLEL,
   interval = [0:None, 0:None, 0:None]
  } : spst.view<[-1:129, -1:130, 0:80], {(?, ?, ?)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
    %out_1 = spst.statement (%in) {} : spst.view<[-1:129, -1:130, 0:80], {(0, 0, 0), (-1, 0, 0), (1, 0, 0), (0, -1, 0), (0, 1, 0)}, f32> -> spst.view<[0:128, 0:129, 0:80], {(0, 0, 0)}, f32> {
      %a = (-4.0 * %in[0, 0, 0]) : f32
      %b = (%a + %in[-1, 0, 0]) : f32
      %c = (%b + %in[1, 0, 0]) : f32
      %d = (%c + %in[0, -1, 0]) : f32
      spst.return (%d + %in[0, 1, 0]) : f32
    }
    %out_mat = spst.materialize (%out_1) : spst.view<[0:128, 0:129, 0:80], {(0, 0, 0)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 1, 0)}, f32>
    %out_2 = spst.statement (%out_1, %out_mat) {} : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>, spst.view<[0:128, 0:128, 0:80], {(0, 1, 0)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
      spst.return (%out_1[0, 0, 0] + %out_mat[0, 1, 0]) : f32
    }
    spst.return %out_2 : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>
  }
  spst.return %res : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>
}
```

Result:
```
kernel<>(stream<f32>[130, 131] _in, stream<f32>[128, 128] _kernel_out_0) {
  place u16 i, u16 j in [1:129 , 1:129] {
    f32[80] res_0_0_0
    f32[80] in_0_0_0
  }
  place u16 i#3, u16 j#3 in [1:129 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 1:130] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 130:131] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 1:130] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 130:131] {
    f32[80] in_0_0_0
  }
  place u16 i#4, u16 j#4 in [1:129 , 129:130] {
    f32[80] in_0_0_0
  }
  place u16 i#4, u16 j#4 in [1:129 , 130:131] {
    f32[80] in_0_0_0
  }
  compute u16 i#5, u16 j#5 in [1:129 , 1:129] {
    await receive(in_0_0_0, _in[i#5, j#5])
  }
  compute u16 i#8, u16 j#8 in [1:129 , 0:1] {
    await receive(in_0_0_0, _in[i#8, j#8])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 1:130] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 0:1] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 130:131] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 1:130] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 0:1] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 130:131] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#9, u16 j#9 in [1:129 , 129:130] {
    await receive(in_0_0_0, _in[i#9, j#9])
  }
  compute u16 i#9, u16 j#9 in [1:129 , 130:131] {
    await receive(in_0_0_0, _in[i#9, j#9])
  }
  phase {
    place u16 i#10, u16 j#10 in [1:129 , 1:129] {
      f32[80] out_mat_0_1_0
      f32[80] out_2_0_0_0
      f32[80] out_1_0_0_0
      f32[80] d_0_0_0
      f32[80] c_0_0_0
      f32[80] b_0_0_0
      f32[80] a_0_0_0
    }
    place u16 i#11, u16 j#11 in [1:129 , 129:130] {
      f32[80] out_1_0_0_0
      f32[80] d_0_0_0
      f32[80] c_0_0_0
      f32[80] b_0_0_0
      f32[80] a_0_0_0
    }
    dataflow u16 i#12, u16 j#12 in [129:130 , 1:130] {
      stream<f32> _stream_in = relative_stream(1, 0)
    }
    dataflow u16 i#13, u16 j#13 in [1:129 , 130:131] {
      stream<f32> _stream_in#1 = relative_stream(0, 1)
    }
    dataflow u16 i#14, u16 j#14 in [1:129 , 0:1] {
      stream<f32> _stream_in#2 = relative_stream(0, -1)
      stream<f32> _stream_out_mat = relative_stream(0, -1)
    }
    dataflow u16 i#15, u16 j#15 in [1:129 , 1:129] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
      stream<f32> _stream_out_mat = relative_stream(0, -1)
      stream<f32> _stream_in = relative_stream(1, 0)
      stream<f32> _stream_in#1 = relative_stream(0, 1)
      stream<f32> _stream_in#2 = relative_stream(0, -1)
    }
    dataflow u16 i#16, u16 j#16 in [0:1 , 1:130] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
    }
    dataflow u16 i#17, u16 j#17 in [1:129 , 129:130] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
      stream<f32> _stream_in = relative_stream(1, 0)
      stream<f32> _stream_in#1 = relative_stream(0, 1)
      stream<f32> _stream_in#2 = relative_stream(0, -1)
    }
    compute u16 i#18, u16 j#18 in [1:129 , 130:131] {
      completion _send_comp = send(in_0_0_0, _stream_in#2)
      await _send_comp
    }
    compute u16 i#19, u16 j#19 in [1:129 , 0:1] {
      completion _send_comp#1 = send(in_0_0_0, _stream_in#1)
      await _send_comp#1
    }
    compute u16 i#20, u16 j#20 in [129:130 , 1:130] {
      completion _send_comp#2 = send(in_0_0_0, _stream_in#3)
      await _send_comp#2
    }
    compute u16 i#21, u16 j#21 in [0:1 , 1:130] {
      completion _send_comp#3 = send(in_0_0_0, _stream_in)
      await _send_comp#3
    }
    compute u16 i#22, u16 j#22 in [1:129 , 1:129] {
      completion _recv_comp = foreach i32 k, f32 x in [0:80], receive(_stream_in#2) {
        out_1_0_0_0[k] = (d_0_0_0 + x)
      }
      completion _send_comp = send(in_0_0_0, _stream_in#2)
      await _send_comp
      await _recv_comp
      completion _recv_comp#1 = foreach i32 k#1, f32 x#1 in [0:80], receive(_stream_in#1) {
        d_0_0_0[k#1] = (c_0_0_0 + x#1)
      }
      completion _send_comp#1 = send(in_0_0_0, _stream_in#1)
      await _send_comp#1
      await _recv_comp#1
      completion _recv_comp#2 = foreach i32 k#2, f32 x#2 in [0:80], receive(_stream_in#3) {
        c_0_0_0[k#2] = (b_0_0_0 + x#2)
      }
      completion _send_comp#2 = send(in_0_0_0, _stream_in#3)
      await _send_comp#2
      await _recv_comp#2
      completion _recv_comp#3 = foreach i32 k#3, f32 x#3 in [0:80], receive(_stream_in) {
        b_0_0_0[k#3] = (a_0_0_0 + x#3)
      }
      completion _send_comp#3 = send(in_0_0_0, _stream_in)
      await _send_comp#3
      await _recv_comp#3
      await map i32 k#4 in [0:80] {
        a_0_0_0[k#4] = (-4.0 * in_0_0_0[k#4])
      }
      completion _recv_comp#4 = foreach i32 k#5, f32 x#4 in [0:80], receive(_stream_out_mat) {
        out_mat_0_1_0[k#5] = x#4
      }
      completion _send_comp#4 = send(out_1_0_0_0, _stream_out_mat)
      await _send_comp#4
      await _recv_comp#4
      await map i32 k#6 in [0:80] {
        out_2_0_0_0[k#6] = (out_1_0_0_0[k#6] + out_mat_0_1_0[k#6])
      }
      await map i32 k#7 in [0:80] {
        res_0_0_0[k#7] = out_2_0_0_0[k#7]
      }
    }
    compute u16 i#23, u16 j#23 in [1:129 , 129:130] {
      completion _recv_comp = foreach i32 k, f32 x in [0:80], receive(_stream_in#2) {
        out_1_0_0_0[k] = (d_0_0_0 + x)
      }
      completion _send_comp = send(in_0_0_0, _stream_in#2)
      await _send_comp
      await _recv_comp
      completion _recv_comp#1 = foreach i32 k#1, f32 x#1 in [0:80], receive(_stream_in#1) {
        d_0 [...]

2024-10-01 13:44 UTC, luxfg commented
Version with automatic 3AC:


```
%pres = spst.program(%in) {} : spst.field<[-1:129, -1:130, 0:80], f32> -> spst.field<[0:128, 0:128, 0:80], f32> {
  %res = spst.computation (%in) {
   schedule = PARALLEL,
   interval = [0:None, 0:None, 0:None]
  } : spst.view<[-1:129, -1:130, 0:80], {(?, ?, ?)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
    %out_1 = spst.statement (%in) {} : spst.view<[-1:129, -1:130, 0:80], {(0, 0, 0), (-1, 0, 0), (1, 0, 0), (0, -1, 0), (0, 1, 0)}, f32> -> spst.view<[0:128, 0:129, 0:80], {(0, 0, 0)}, f32> {
      spst.return ((-4.0 * %in[0, 0, 0]) + (%in[-1, 0, 0] + (%in[1, 0, 0] + (%in[0, -1, 0] + %in[0, 1, 0])))) : f32
    }
    %out_mat = spst.materialize (%out_1) : spst.view<[0:128, 0:129, 0:80], {(0, 0, 0)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 1, 0)}, f32>
    %out_2 = spst.statement (%out_1, %out_mat) {} : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>, spst.view<[0:128, 0:128, 0:80], {(0, 1, 0)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
      spst.return (%out_1 + %out_mat[0, 1, 0]) : f32
    }
    spst.return %out_2 : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>
  }
  spst.return %res : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>
}
```

3AC:
```
%pres = spst.program(%in) {} : spst.field<[-1:129, -1:130, 0:80], f32> -> spst.field<[0:128, 0:128, 0:80], f32> {
  %res = spst.computation (%in) {
   schedule = PARALLEL,
   interval = [0:None, 0:None, 0:None]
  } : spst.view<[-1:129, -1:130, 0:80], {(?, ?, ?)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
    %out_1 = spst.statement (%in) {} : spst.view<[-1:129, -1:130, 0:80], {(0, 0, 0), (-1, 0, 0), (1, 0, 0), (0, -1, 0), (0, 1, 0)}, f32> -> spst.view<[0:128, 0:129, 0:80], {(0, 0, 0)}, f32> {
      %_temp#4 = %in[0, -1, 0] : f32
      %_temp#3 = (%_temp#4[0, 0, 0] + %in[0, 1, 0]) : f32
      %_temp#2 = (%in[1, 0, 0] + %_temp#3[0, 0, 0]) : f32
      %_temp = (%in[-1, 0, 0] + %_temp#2[0, 0, 0]) : f32
      %_temp#1 = (-4.0 * %in[0, 0, 0]) : f32
      spst.return (%_temp#1[0, 0, 0] + %_temp[0, 0, 0]) : f32
    }
    %out_mat = spst.materialize (%out_1) : spst.view<[0:128, 0:129, 0:80], {(0, 0, 0)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 1, 0)}, f32>
    %out_2 = spst.statement (%out_1, %out_mat) {} : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>, spst.view<[0:128, 0:128, 0:80], {(0, 1, 0)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
      spst.return (%out_1[0, 0, 0] + %out_mat[0, 1, 0]) : f32
    }
    spst.return %out_2 : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>
  }
  spst.return %res : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>
}
```

```
kernel<>(stream<f32>[130, 131] _in, stream<f32>[128, 128] _kernel_out_0) {
  place u16 i, u16 j in [1:129 , 1:129] {
    f32[80] res_0_0_0
    f32[80] in_0_0_0
  }
  place u16 i#3, u16 j#3 in [1:129 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 1:130] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 130:131] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 1:130] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 130:131] {
    f32[80] in_0_0_0
  }
  place u16 i#4, u16 j#4 in [1:129 , 129:130] {
    f32[80] in_0_0_0
  }
  place u16 i#4, u16 j#4 in [1:129 , 130:131] {
    f32[80] in_0_0_0
  }
  compute u16 i#5, u16 j#5 in [1:129 , 1:129] {
    await receive(in_0_0_0, _in[i#5, j#5])
  }
  compute u16 i#8, u16 j#8 in [1:129 , 0:1] {
    await receive(in_0_0_0, _in[i#8, j#8])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 1:130] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 0:1] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 130:131] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 1:130] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 0:1] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 130:131] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#9, u16 j#9 in [1:129 , 129:130] {
    await receive(in_0_0_0, _in[i#9, j#9])
  }
  compute u16 i#9, u16 j#9 in [1:129 , 130:131] {
    await receive(in_0_0_0, _in[i#9, j#9])
  }
  phase {
    place u16 i#10, u16 j#10 in [1:129 , 1:129] {
      f32[80] out_mat_0_1_0
      f32[80] out_2_0_0_0
      f32[80] out_1_0_0_0
      f32[80] _temp_0_0_0
      f32[80] _temp_0_0_0#1
      f32[80] _temp_0_0_0#2
      f32[80] _temp_0_0_0#3
      f32[80] _temp_0_0_0#4
    }
    place u16 i#11, u16 j#11 in [1:129 , 129:130] {
      f32[80] out_1_0_0_0
      f32[80] _temp_0_0_0
      f32[80] _temp_0_0_0#1
      f32[80] _temp_0_0_0#2
      f32[80] _temp_0_0_0#3
      f32[80] _temp_0_0_0#4
    }
    dataflow u16 i#12, u16 j#12 in [129:130 , 1:130] {
      stream<f32> _stream_in = relative_stream(1, 0)
    }
    dataflow u16 i#13, u16 j#13 in [1:129 , 130:131] {
      stream<f32> _stream_in#1 = relative_stream(0, 1)
    }
    dataflow u16 i#14, u16 j#14 in [1:129 , 0:1] {
      stream<f32> _stream_in#2 = relative_stream(0, -1)
      stream<f32> _stream_out_mat = relative_stream(0, -1)
    }
    dataflow u16 i#15, u16 j#15 in [1:129 , 1:129] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
      stream<f32> _stream_out_mat = relative_stream(0, -1)
      stream<f32> _stream_in = relative_stream(1, 0)
      stream<f32> _stream_in#1 = relative_stream(0, 1)
      stream<f32> _stream_in#2 = relative_stream(0, -1)
    }
    dataflow u16 i#16, u16 j#16 in [0:1 , 1:130] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
    }
    dataflow u16 i#17, u16 j#17 in [1:129 , 129:130] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
      stream<f32> _stream_in = relative_stream(1, 0)
      stream<f32> _stream_in#1 = relative_stream(0, 1)
      stream<f32> _stream_in#2 = relative_stream(0, -1)
    }
    compute u16 i#18, u16 j#18 in [1:129 , 0:1] {
      completion _send_comp = send(in_0_0_0, _stream_in#1)
      await _send_comp
    }
    compute u16 i#19, u16 j#19 in [1:129 , 130:131] {
      completion _send_comp#1 = send(in_0_0_0, _stream_in#2)
      await _send_comp#1
    }
    compute u16 i#20, u16 j#20 in [129:130 , 1:130] {
      completion _send_comp#2 = send(in_0_0_0, _stream_in#3)
      await _send_comp#2
    }
    compute u16 i#21, u16 j#21 in [0:1 , 1:130] {
      completion _send_comp#3 = send(in_0_0_0, _stream_in)
      await _send_comp#3
    }
    compute u16 i#22, u16 j#22 in [1:129 , 1:129] {
      completion _recv_comp = foreach i32 k, f32 x in [0:80], receive(_stream_in#1) {
        _temp_0_0_0[k] = x
      }
      completion _send_comp = send(in_0_0_0, _stream_in#1)
      await _send_comp
      await _recv_comp
      completion _recv_comp#1 = foreach i32 k#1, f32 x#1 in [0:80], receive(_stream_in#2) {
        _temp_0_0_0#1[k#1] = (_temp_0_0_0 + x#1)
      }
      completion _send_comp#1 = send(in_0_0_0, _stream_in#2)
      await _send_comp#1
      await _recv_comp#1
      completion _recv_comp#2 = foreach i32 k#2, f32 x#2 in [0:80], receive(_stream_in#3) {
        _temp_0_0_0#2[k#2] = (_temp_0_0_0#1 + x#2)
      }
      completion _send_comp#2 = send(in_0_0_0, _stream_in#3)
      await _send_comp#2
      await _recv_comp#2
      completion _recv_comp#3 = foreach i32 k#3, f32 x#3 in [0:80], receive(_stream_in) {
        _temp_0_0_0#3[k#3] = (_temp_0_0_0#2 + x#3)
      }
      completion _send_comp#3 = send(in_0_0_0, _stream_in)
      await _send_comp#3
      await _recv_comp#3
      await map i32 k#4 in [0:80] {
        _temp_0_0_0#4[k#4] = (-4.0 * in_0_0_0[k#4])
      }
      await map i32 k#5 in [0:80] {
        out_1_0_0_0[k#5] = (_temp_0_0_0#4[k#5] + _temp_0_0_0#3[k#5])
      }
      completion _recv_comp#4 = foreach i32 k#6, f32 x#4 in [0:80], receive(_stream_out_mat)  [...]

2024-10-04 13:20 UTC, luxfg commented
```
%pres, %pres2 = spst.program @uvbke(%arg0, %arg1, %arg2, %arg3) {} : spst.field<[0:128, -1:128, 0:80], f32>, spst.field<[-1:128, 0:128, 0:80], f32>, spst.field<[0:128, 0:128, 0:80], f32>, spst.field<[0:128, 0:128, 0:80], f32> -> spst.field<[0:128, 0:128, 0:80], f32>, spst.field<[0:128, 0:128, 0:80], f32> {
  %arg4, %arg5 = spst.computation (%arg0, %arg1, %arg2, %arg3) {
   schedule = PARALLEL,
   interval = [None:None, None:None, None:None]
  } : spst.view<[0:128, -1:128, 0:80], {(?, ?, ?)}, f32>, spst.view<[-1:128, 0:128, 0:80], {(?, ?, ?)}, f32>, spst.view<[0:128, 0:128, 0:80], {(?, ?, ?)}, f32>, spst.view<[0:128, 0:128, 0:80], {(?, ?, ?)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>, spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
    %arg4 = spst.statement (%arg0, %arg1, %arg2, %arg3) {} : spst.view<[0:128, -1:128, 0:80], {(0, -1, 0), (0, 0, 0)}, f32>, spst.view<[-1:128, 0:128, 0:80], {(-1, 0, 0), (0, 0, 0)}, f32>, spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>, spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
      spst.return %23[0, 0, 0] : f32
      %23 = (%arg3[0, 0, 0] * %21[0, 0, 0]) : f32
      %_temp#1 = (%19[0, 0, 0] - %16[0, 0, 0]) : f32
      %21 = (112.5 * %_temp#1[0, 0, 0]) : f32
      %19 = (%arg0[0, -1, 0] + %arg0[0, 0, 0]) : f32
      %_temp = (%arg1[-1, 0, 0] + %arg1[0, 0, 0]) : f32
      %16 = (%_temp[0, 0, 0] * %arg2[0, 0, 0]) : f32
    }
    %arg5 = spst.statement (%arg0, %arg1, %arg2, %arg3) {} : spst.view<[0:128, -1:128, 0:80], {(0, -1, 0), (0, 0, 0)}, f32>, spst.view<[-1:128, 0:128, 0:80], {(-1, 0, 0), (0, 0, 0)}, f32>, spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32>, spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> -> spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, f32> {
      spst.return %23[0, 0, 0] : f32
      %23 = (%arg3[0, 0, 0] * %21[0, 0, 0]) : f32
      %_temp#3 = (%19[0, 0, 0] - %16[0, 0, 0]) : f32
      %21 = (112.5 * %_temp#3[0, 0, 0]) : f32
      %19 = (%arg1[-1, 0, 0] + %arg1[0, 0, 0]) : f32
      %_temp#2 = (%arg0[0, -1, 0] + %arg0[0, 0, 0]) : f32
      %16 = (%_temp#2[0, 0, 0] * %arg2[0, 0, 0]) : f32
    }
    spst.return %arg4, %arg5 : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, UNKNOWN>, spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, UNKNOWN>
  }
  spst.return %arg4, %arg5 : spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, UNKNOWN>, spst.view<[0:128, 0:128, 0:80], {(0, 0, 0)}, UNKNOWN>
}
```

```
kernel @uvbke<>(stream<f32>[128, 129] _arg0, stream<f32>[129, 128] _arg1, stream<f32>[128, 128] _arg2, stream<f32>[128, 128] _arg3, stream<f32>[128, 128] _kernel_out_0, stream<f32>[128, 128] _kernel_out_1) {
  place u16 i, u16 j in [1:129 , 1:129] {
    f32[80] arg2_0_0_0
    f32[80] arg3_0_0_0
    f32[80] arg4_0_0_0
    f32[80] arg5_0_0_0
    f32[80] arg0_0_0_0
    f32[80] arg1_0_0_0
  }
  place u16 i#1, u16 j#1 in [1:129 , 0:1] {
    f32[80] arg0_0_0_0
  }
  place u16 i#2, u16 j#2 in [0:1 , 1:129] {
    f32[80] arg1_0_0_0
  }
  compute u16 i#3, u16 j#3 in [1:129 , 1:129] {
    await receive(arg2_0_0_0, _arg2[i#3, j#3])
    await receive(arg3_0_0_0, _arg3[i#3, j#3])
    await receive(arg0_0_0_0, _arg0[i#3, j#3])
    await receive(arg1_0_0_0, _arg1[i#3, j#3])
  }
  compute u16 i#4, u16 j#4 in [1:129 , 0:1] {
    await receive(arg0_0_0_0, _arg0[i#4, j#4])
  }
  compute u16 i#5, u16 j#5 in [0:1 , 1:129] {
    await receive(arg1_0_0_0, _arg1[i#5, j#5])
  }
  phase {
    place u16 i#6, u16 j#6 in [1:129 , 1:129] {
      f32[80] arg4_0_0_0#1
      f32[80] 23_0_0_0
      f32[80] _temp_0_0_0
      f32[80] 21_0_0_0
      f32[80] 19_0_0_0
      f32[80] _temp_0_0_0#1
      f32[80] 16_0_0_0
      f32[80] arg5_0_0_0#1
      f32[80] 23_0_0_0#1
      f32[80] _temp_0_0_0#2
      f32[80] 21_0_0_0#1
      f32[80] 19_0_0_0#1
      f32[80] _temp_0_0_0#3
      f32[80] 16_0_0_0#1
    }
    dataflow u16 i#7, u16 j#7 in [1:129 , 1:129] {
      stream<f32> _stream_arg0 = relative_stream(0, 1)
      stream<f32> _stream_arg1 = relative_stream(1, 0)
      stream<f32> _stream_arg0#1 = relative_stream(0, 1)
      stream<f32> _stream_arg1#1 = relative_stream(1, 0)
    }
    dataflow u16 i#8, u16 j#8 in [1:129 , 129:130] {
      stream<f32> _stream_arg0 = relative_stream(0, 1)
      stream<f32> _stream_arg0#1 = relative_stream(0, 1)
    }
    dataflow u16 i#9, u16 j#9 in [129:130 , 1:129] {
      stream<f32> _stream_arg1 = relative_stream(1, 0)
      stream<f32> _stream_arg1#1 = relative_stream(1, 0)
    }
    compute u16 i#10, u16 j#10 in [1:129 , 1:129] {
      await map i32 k in [0:80] {
        arg4_0_0_0#1[k] = 23_0_0_0#1[k]
      }
      await map i32 k#1 in [0:80] {
        23_0_0_0#1[k#1] = (arg3_0_0_0[k#1] * 21_0_0_0#1[k#1])
      }
      await map i32 k#2 in [0:80] {
        _temp_0_0_0[k#2] = (19_0_0_0#1[k#2] - 16_0_0_0#1[k#2])
      }
      await map i32 k#3 in [0:80] {
        21_0_0_0#1[k#3] = (112.5 * _temp_0_0_0[k#3])
      }
      completion _recv_comp = foreach i32 k#4, f32 x in [0:80], receive(_stream_arg0) {
        19_0_0_0#1[k#4] = (arg0_0_0_0 + x)
      }
      completion _send_comp = send(arg0_0_0_0, _stream_arg0)
      await _send_comp
      await _recv_comp
      completion _recv_comp#1 = foreach i32 k#5, f32 x#1 in [0:80], receive(_stream_arg1) {
        _temp_0_0_0#1[k#5] = (arg1_0_0_0 + x#1)
      }
      completion _send_comp#1 = send(arg1_0_0_0, _stream_arg1)
      await _send_comp#1
      await _recv_comp#1
      await map i32 k#6 in [0:80] {
        16_0_0_0#1[k#6] = (_temp_0_0_0#1[k#6] * arg2_0_0_0[k#6])
      }
      await map i32 k#7 in [0:80] {
        arg5_0_0_0#1[k#7] = 23_0_0_0#1[k#7]
      }
      await map i32 k#8 in [0:80] {
        23_0_0_0#1[k#8] = (arg3_0_0_0[k#8] * 21_0_0_0#1[k#8])
      }
      await map i32 k#9 in [0:80] {
        _temp_0_0_0#2[k#9] = (19_0_0_0#1[k#9] - 16_0_0_0#1[k#9])
      }
      await map i32 k#10 in [0:80] {
        21_0_0_0#1[k#10] = (112.5 * _temp_0_0_0#2[k#10])
      }
      completion _recv_comp#2 = foreach i32 k#11, f32 x#2 in [0:80], receive(_stream_arg1#1) {
        19_0_0_0#1[k#11] = (arg1_0_0_0 + x#2)
      }
      completion _send_comp#2 = send(arg1_0_0_0, _stream_arg1#1)
      await _send_comp#2
      await _recv_comp#2
      completion _recv_comp#3 = foreach i32 k#12, f32 x#3 in [0:80], receive(_stream_arg0#1) {
        _temp_0_0_0#3[k#12] = (arg0_0_0_0 + x#3)
      }
      completion _send_comp#3 = send(arg0_0_0_0, _stream_arg0#1)
      await _send_comp#3
      await _recv_comp#3
      await map i32 k#13 in [0:80] {
        16_0_0_0#1[k#13] = (_temp_0_0_0#3[k#13] * arg2_0_0_0[k#13])
      }
      await map i32 k#14 in [0:80] {
        arg4_0_0_0#1[k#14] = arg4_0_0_0#1[k#14]
      }
      await map i32 k#15 in [0:80] {
        arg5_0_0_0#1[k#15] = arg5_0_0_0#1[k#15]
      }
    }
    compute u16 i#11, u16 j#11 in [1:129 , 0:1] {
      completion _send_comp = send(arg0_0_0_0, _stream_arg0)
      await _send_comp
      completion _send_comp#3 = send(arg0_0_0_0, _stream_arg0#1)
      await _send_comp#3
    }
    compute u16 i#12, u16 j#12 in [0:1 , 1:129] {
      completion _send_comp#1 = send(arg1_0_0_0, _stream_arg1)
      await _send_comp#1
      completion _send_comp#2 = send(arg1_0_0_0, _stream_arg1#1)
      await _send_comp#2
    }
  }
  phase {
    compute u32 i#13, u32 j#13 in [1:129 , 1:129] {
      await send(arg4_0_0_0#1, kernel_out_0[(i#13 - 1), (j#13 - 1)])
    }
    compute u32 i#14, u32 j#14 in [1:129 , 1:129] {
      await send(arg5_0_0_0#1, kernel_out_1[(i#14 - 1), (j#14 - 1)])
    }
  }
}
```

2024-10-05 01:22 UTC, tbennun requested changes
I reviewed this. I am aware this is not the complete lowering process but I still have some questions. Let's discuss.

2024-10-05 01:22 UTC, tbennun commented on tests/test_tree_matching.py
> +        print(result)
you have a lot of printouts in your tests, are those necessary?

2024-10-05 01:22 UTC, tbennun commented on tests/test_lowering_stencil_to_spatial.py
> +        #type_inference.infer_types(program, domain=[128, 128, 80])
no longer necessary as lowering does that?

2024-10-05 01:22 UTC, tbennun commented on tests/test_lowering_stencil_to_spatial.py
> +        type_inference.infer_field_domains(program, domain)
same

2024-10-05 01:22 UTC, tbennun commented on tests/test_lowering_stencil_to_spatial.py
> +        print(program.as_ir())
printouts

2024-10-05 01:22 UTC, tbennun commented on tests/test_spatial_irnodes.py
This file is empty, please remove

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +        return Subscript(args[0], list(args[1]))
We should change the entry in `lark_to_ast.py` instead in this case.

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +            print(self.value.value, "Unary")
```suggestion
```

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/match_tree.py
> +    def walk_tree(self):
Please add docstring with walk order.

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/match_tree.py
> +    def match_string(self, match: dict['TreeNode', bool]):
return type hint, maybe short docstring

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/match_tree.py
> +# Abstract Tree class
move these comments (apply to all classes in this file) into the class docstring for clarity.

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/match_tree.py
> +class MatchingBaseNode(Generic[NVar], TreeNode[str]):
Unclear to me what this class and the `from_base_node` do. Please add some docs, thanks!

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/match_tree.py
> +# Helper function to collect paths from root to leaf
I would also move this to a short docstring. No need to document all param types but just this function.

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/tree_matching.py
> +class Match:
docstrings are missing for classes

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/tree_matching.py
> +    def match_pattern(self, subject: BaseNode) -> list[Match]:
1. should subject not be of type `BaseNodeT`?
2. since this is the main entry point to the pattern matcher, please add a docstring (for example, is the subject the root of a tree? unclear from type hints alone)

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/tree_matching.py
> +    Math a pattern tree to a subject tree using the approach by Hoffmann and O’Donnell
```suggestion
    Match a pattern tree to a subject tree using the approach by Hoffmann and O’Donnell
```

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/common/tree_matching.py
> +        """
Yes, but what does `wildcards` contain, and what should I return? Please improve docstring here.

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/spatial_ir/grid_geometry.py
> +@dataclass(frozen=True)
Everything looks good :)

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/canonical_expression.py
> +class CanonicalExpressionVisitor(NodeVisitor):
The class name does not hint at three-address code. Also, the file's docstring should be the class'.

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial.py
> +    # TODO: Extent to scalar types & constants, detect write-only / readonly fields
The second part of the TODO is clearly something that should still be done (in the next PR I assume), but what is the first part of it? Don't we already use the extent and scalar types?

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial.py
> +import spatialstencil.syntax.spatial_ir.irnodes as spa
Nice name 👍

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial_compute.py
> +        :return:
```suggestion
```

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial_compute.py
> +class HorizontalStencilTransformer(
I don't understand the need in this class (and the `MapTransformer`s) to be so explicit with the types of operations you transform. We have a very clear mapping between sast.BinaryOperator and spa.BinaryOperator, etc.

I am wondering if we should not do this in two separate steps: one to convert the computation types, and one to wrap with map vs. foreach based on other analyses that you do (e.g., in `CanonicalExpressionVisitor`).

We can discuss this.

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial_compute.py
> +                                   (line_nr, spa.AwaitCompletionStatement(send_comp_id)))
I wonder if we should have a separate pass that "pushes" the completion `awaits` as far down as possible. Thoughts?
(Obviously should be separate from this PR and definitely this code)

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial_dataflow.py
> +        :return:
```suggestion
```

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial_place.py
> +class FieldMetadata:
Is this necessary or can you use a `spa.FieldDeclaration` instead?

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial_place.py
> +        # TODO: Extend to scalar types
Will this be handled in another PR or should we try for making scalars into array fields explicitly in the first version of the entire code?

2024-10-05 01:22 UTC, tbennun commented on spatialstencil/lowering/stencil_to_spatial_place.py
> +            # TODO: Extend to scalar types
see comment below

2024-10-07 08:32 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/canonical_expression.py
> +class CanonicalExpressionVisitor(NodeVisitor):
I avoided it because I wanted to avoid confusing anyone that we were constructing a data structure that resembles something that compilers use for 3AC. As far as I have read, many compilers use optimized representations for 3AC, and I wanted to clarify that it is about transforming the expressions, not modifying the ir representation.

2024-10-07 08:38 UTC, luxfg commented on spatialstencil/lowering/stencil_to_spatial.py
> +    # TODO: Extent to scalar types & constants, detect write-only / readonly fields
Scalar types are note yet support in lowering. Not for any particular reason, just because it is not high priority.

2024-10-07 08:38 UTC, luxfg commented on spatialstencil/lowering/stencil_to_spatial.py
> +    # TODO: Extent to scalar types & constants, detect write-only / readonly fields
I will support scalar types in the next PR.

2024-10-07 08:39 UTC, luxfg commented on spatialstencil/lowering/stencil_to_spatial.py
> +    # TODO: Extent to scalar types & constants, detect write-only / readonly fields
The comment was confusing because 'Extent' was a type for 'Extend', sry.

2024-10-07 08:45 UTC, luxfg commented on spatialstencil/lowering/stencil_to_spatial_compute.py
> +class HorizontalStencilTransformer(
This could also be a way to do it. The disadvantage of the current approach is the need to enumerate all possible expression patterns. There could be indeed a recursive way to express this succinctly. It is a bit subtle though, because what is in another branch of the expression could impact the code that is generated. A two-phase approach could get around this, but I would need to spend a bit more time to figure out the corner cases. Let's discuss.

2024-10-07 08:46 UTC, luxfg commented on spatialstencil/lowering/stencil_to_spatial_compute.py
> +                                   (line_nr, spa.AwaitCompletionStatement(send_comp_id)))
Yes, could be possible, though first need to argue if there is any advantage. There could also be a real cost in doing so because it means more tasks are active concurrently, which increases the number of used task ids.

2024-10-07 08:54 UTC, luxfg commented on spatialstencil/lowering/stencil_to_spatial_place.py
> +        # TODO: Extend to scalar types
I would use another PR.

2024-10-07 09:10 UTC, luxfg commented on spatialstencil/syntax/common/tree_matching.py
> +    def match_pattern(self, subject: BaseNode) -> list[Match]:
Agreed.

2024-10-07 14:07 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/canonical_expression.py
> +class CanonicalExpressionVisitor(NodeVisitor):
Maybe CanonicalExpressionTransformer

2024-10-07 14:07 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/canonical_expression.py
> +class CanonicalExpressionVisitor(NodeVisitor):
or CanonicalizeExpression

2024-10-07 15:00 UTC, luxfg commented
Here is the horizontal laplacian stencil:

```
kernel<>(stream<f32>[130, 131] _in, stream<f32>[128, 128] _kernel_out_0) {
  place u16 i, u16 j in [1:129 , 1:129] {
    f32[80] res_0_0_0
    f32[80] in_0_0_0
  }
  place u16 i#3, u16 j#3 in [1:129 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 1:130] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#1, u16 j#1 in [0:1 , 130:131] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 1:130] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 0:1] {
    f32[80] in_0_0_0
  }
  place u16 i#2, u16 j#2 in [129:130 , 130:131] {
    f32[80] in_0_0_0
  }
  place u16 i#4, u16 j#4 in [1:129 , 129:130] {
    f32[80] in_0_0_0
  }
  place u16 i#4, u16 j#4 in [1:129 , 130:131] {
    f32[80] in_0_0_0
  }
  compute u16 i#5, u16 j#5 in [1:129 , 1:129] {
    await receive(in_0_0_0, _in[i#5, j#5])
  }
  compute u16 i#8, u16 j#8 in [1:129 , 0:1] {
    await receive(in_0_0_0, _in[i#8, j#8])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 1:130] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 0:1] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#6, u16 j#6 in [0:1 , 130:131] {
    await receive(in_0_0_0, _in[i#6, j#6])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 1:130] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 0:1] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#7, u16 j#7 in [129:130 , 130:131] {
    await receive(in_0_0_0, _in[i#7, j#7])
  }
  compute u16 i#9, u16 j#9 in [1:129 , 129:130] {
    await receive(in_0_0_0, _in[i#9, j#9])
  }
  compute u16 i#9, u16 j#9 in [1:129 , 130:131] {
    await receive(in_0_0_0, _in[i#9, j#9])
  }
  phase {
    place u16 i#10, u16 j#10 in [1:129 , 1:129] {
      f32[80] out_mat_0_1_0
      f32[80] out_2_0_0_0
      f32[80] out_1_0_0_0
      f32[80] _temp_0_0_0
      f32[80] _temp_0_0_0#1
      f32[80] _temp_0_0_0#2
      f32[80] _temp_0_0_0#3
      f32[80] _temp_0_0_0#4
    }
    place u16 i#11, u16 j#11 in [1:129 , 129:130] {
      f32[80] out_1_0_0_0
      f32[80] _temp_0_0_0
      f32[80] _temp_0_0_0#1
      f32[80] _temp_0_0_0#2
      f32[80] _temp_0_0_0#3
      f32[80] _temp_0_0_0#4
    }
    dataflow u16 i#12, u16 j#12 in [129:130 , 1:130] {
      stream<f32> _stream_in = relative_stream(1, 0)
    }
    dataflow u16 i#13, u16 j#13 in [1:129 , 130:131] {
      stream<f32> _stream_in#1 = relative_stream(0, 1)
    }
    dataflow u16 i#14, u16 j#14 in [1:129 , 0:1] {
      stream<f32> _stream_in#2 = relative_stream(0, -1)
      stream<f32> _stream_out_mat = relative_stream(0, -1)
    }
    dataflow u16 i#15, u16 j#15 in [1:129 , 1:129] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
      stream<f32> _stream_out_mat = relative_stream(0, -1)
      stream<f32> _stream_in = relative_stream(1, 0)
      stream<f32> _stream_in#1 = relative_stream(0, 1)
      stream<f32> _stream_in#2 = relative_stream(0, -1)
    }
    dataflow u16 i#16, u16 j#16 in [0:1 , 1:130] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
    }
    dataflow u16 i#17, u16 j#17 in [1:129 , 129:130] {
      stream<f32> _stream_in#3 = relative_stream(-1, 0)
      stream<f32> _stream_in = relative_stream(1, 0)
      stream<f32> _stream_in#1 = relative_stream(0, 1)
      stream<f32> _stream_in#2 = relative_stream(0, -1)
    }
    compute u16 i#18, u16 j#18 in [1:129 , 0:1] {
      completion _send_comp = send(in_0_0_0, _stream_in#1)
      await _send_comp
    }
    compute u16 i#19, u16 j#19 in [1:129 , 130:131] {
      completion _send_comp#1 = send(in_0_0_0, _stream_in#2)
      await _send_comp#1
    }
    compute u16 i#20, u16 j#20 in [129:130 , 1:130] {
      completion _send_comp#2 = send(in_0_0_0, _stream_in#3)
      await _send_comp#2
    }
    compute u16 i#21, u16 j#21 in [0:1 , 1:130] {
      completion _send_comp#3 = send(in_0_0_0, _stream_in)
      await _send_comp#3
    }
    compute u16 i#22, u16 j#22 in [1:129 , 1:129] {
      completion _recv_comp = foreach i32 k, f32 x in [0:80], receive(_stream_in#1) {
        _temp_0_0_0[k] = x
      }
      completion _send_comp = send(in_0_0_0, _stream_in#1)
      await _send_comp
      await _recv_comp
      completion _recv_comp#1 = foreach i32 k#1, f32 x#1 in [0:80], receive(_stream_in#2) {
        _temp_0_0_0#1[k#1] = (_temp_0_0_0 + x#1)
      }
      completion _send_comp#1 = send(in_0_0_0, _stream_in#2)
      await _send_comp#1
      await _recv_comp#1
      completion _recv_comp#2 = foreach i32 k#2, f32 x#2 in [0:80], receive(_stream_in#3) {
        _temp_0_0_0#2[k#2] = (_temp_0_0_0#1 + x#2)
      }
      completion _send_comp#2 = send(in_0_0_0, _stream_in#3)
      await _send_comp#2
      await _recv_comp#2
      completion _recv_comp#3 = foreach i32 k#3, f32 x#3 in [0:80], receive(_stream_in) {
        _temp_0_0_0#3[k#3] = (_temp_0_0_0#2 + x#3)
      }
      completion _send_comp#3 = send(in_0_0_0, _stream_in)
      await _send_comp#3
      await _recv_comp#3
      await map i32 k#4 in [0:80] {
        _temp_0_0_0#4[k#4] = (-4.0 * in_0_0_0[k#4])
      }
      await map i32 k#5 in [0:80] {
        out_1_0_0_0[k#5] = (_temp_0_0_0#4[k#5] + _temp_0_0_0#3[k#5])
      }
      completion _recv_comp#4 = foreach i32 k#6, f32 x#4 in [0:80], receive(_stream_out_mat) {
        out_mat_0_1_0[k#6] = x#4
      }
      completion _send_comp#4 = send(out_1_0_0_0, _stream_out_mat)
      await _send_comp#4
      await _recv_comp#4
      await map i32 k#7 in [0:80] {
        out_2_0_0_0[k#7] = (out_1_0_0_0[k#7] + out_mat_0_1_0[k#7])
      }
      await map i32 k#8 in [0:80] {
        res_0_0_0[k#8] = out_2_0_0_0[k#8]
      }
    }
    compute u16 i#23, u16 j#23 in [1:129 , 129:130] {
      completion _recv_comp = foreach i32 k, f32 x in [0:80], receive(_stream_in#1) {
        _temp_0_0_0[k] = x
      }
      completion _send_comp = send(in_0_0_0, _stream_in#1)
      await _send_comp
      await _recv_comp
      completion _recv_comp#1 = foreach i32 k#1, f32 x#1 in [0:80], receive(_stream_in#2) {
        _temp_0_0_0#1[k#1] = (_temp_0_0_0 + x#1)
      }
      completion _send_comp#1 = send(in_0_0_0, _stream_in#2)
      await _send_comp#1
      await _recv_comp#1
      completion _recv_comp#2 = foreach i32 k#2, f32 x#2 in [0:80], receive(_stream_in#3) {
        _temp_0_0_0#2[k#2] = (_temp_0_0_0#1 + x#2)
      }
      completion _send_comp#2 = send(in_0_0_0, _stream_in#3)
      await _send_comp#2
      await _recv_comp#2
      completion _recv_comp#3 = foreach i32 k#3, f32 x#3 in [0:80], receive(_stream_in) {
        _temp_0_0_0#3[k#3] = (_temp_0_0_0#2 + x#3)
      }
      completion _send_comp#3 = send(in_0_0_0, _stream_in)
      await _send_comp#3
      await _recv_comp#3
      await map i32 k#4 in [0:80] {
        _temp_0_0_0#4[k#4] = (-4.0 * in_0_0_0[k#4])
      }
      await map i32 k#5 in [0:80] {
        out_1_0_0_0[k#5] = (_temp_0_0_0#4[k#5] + _temp_0_0_0#3[k#5])
      }
      completion _send_comp#4 = send(out_1_0_0_0, _stream_out_mat)
      await _send_comp#4
    }
  }
  phase {
    compute u32 i#24, u32 j#24 in [1:129 , 1:129] {
      await send(res_0_0_0, kernel_out_0[(i#24 - 1), (j#24 - 1)])
    }
  }
}
```

2024-10-07 15:02 UTC, tbennun approved these changes

2024-10-07 21:34 UTC, merged