Add & Fix examples, docs
spcl/spada pull request #16
Opened 2024-10-08 09:15 UTC by luxfg

I fixed some the examples and added two simple vertical stencils, a forward and a backward, and a 4 PE 2-phase reduce.

2024-10-08 09:19 UTC, luxfg commented
Note that tests are failing because of issues in the parsing for hops and for-loops. Could you investigate?

2024-10-08 09:35 UTC, tbennun requested changes
Looks good, see comments

2024-10-08 09:35 UTC, tbennun commented on irspec/docs/spatial/examples.md
> +      receive(lap_field[i, j], local_input);
inverted arguments?

2024-10-08 09:35 UTC, tbennun commented on irspec/docs/spatial/examples.md
> +        send(datacol_l, datacol[i, j]);
correct syntax should always be either `await send` or `completion c = send`, applies to all the other examples.

2024-10-08 09:35 UTC, tbennun commented on irspec/docs/spatial/examples.md
> +        dataflow i16 i, i16 j in [1:I, 1:J] {
computation in dataflow

2024-10-08 09:35 UTC, tbennun commented on irspec/docs/spatial/examples.md
> +            comp_west = send(x, westwards);
```suggestion
            completion comp_west = send(x, westwards);
```

2024-10-08 09:35 UTC, tbennun commented on irspec/docs/spatial/examples.md
> +            comp_east = send(x, eastwards);
same as above

2024-10-08 09:35 UTC, tbennun commented on irspec/docs/spatial/spatial.md
> +### Receive Statement
thx for adding these two elements!!

2024-10-08 10:27 UTC, luxfg commented
Ok, I fixed the examples and the parser & ir.

2024-10-09 20:13 UTC, tbennun approved these changes

2024-10-10 06:40 UTC, merged