AST -> Stencil IR
spcl/spada pull request #5
Opened 2024-06-13 16:09 UTC by tbennun

Implements a parser for GT4Py embedded Python DSL, a parser/printer for the Stencil IR, and lowering from GT4Py to the Stencil IR

Components:
- [x] GT4Py syntax parser
   - [x] Conditionals
- [x] Stencil IR object-oriented definition
  - [x] Lark support
- [x] IR node traversal and transformation (GT4Py, Stencil IR)
- [x] Lowering GT4Py AST to Stencil IR
  - [x] Field versioning
  - [x] Constant propagation
  - [x] Type inference
     - [x] Input/output
     - [x] Scalar type
     - [x] Extents
     - [x] Domain
  - [x] Materialize everything (as IR node transformation)

Stencils:
- [x] hdiff
- [x] vadv
- [x] hdiffsa
- [x] hdiffsmag
- [x] uvbke

2024-08-13 07:27 UTC, tbennun commented
Ready for review @glukas

2024-08-13 13:58 UTC, tbennun commented on irspec/docs/stencil/stencil.md
> +    For example, `spst.cartesian<1, ?, 3>` is equivalent to `spst.cartesian<1, ?, 3>`
What does this mean?

2024-08-13 14:58 UTC, luxfg requested changes
I have reviewed helpers.py, irnodes.py, and the docs in detail. I will continue later / tomorrow with the rest.

2024-08-13 14:58 UTC, luxfg commented on irspec/docs/stencil/stencil.md
> +  * For the purposes of type promotion, `bool` is considered a signed integral 1-bit value.
is bool signed 1 bit or unsigned 1 bit?

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    def validate(self) -> None:
Arguably validate should be part of BaseNode

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    def pretty(self) -> str:
Also pretty could probably be part of BaseNode

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +class Domain(Node):
Could it make sense to have a class or interface 'BaseType' and have all types inherit from that? 
This could for example contain the 'is_subtype_of' / 'is_supertype_of' this could allow some generic type checking.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +def walk(node: BaseNode):
could be a method of BaseNode?

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +Provides basic AST/IR utilities for traversal, transformation, and find/replacement.
helpers is an undescriptive name. Consider changing to irnode.py.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +class BaseNode:
I think we should have 'Operation', 'Type', and 'BasicBlock' as interfaces or abstract base classes defined maybe in this file so we can reuse them across different IRs.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +class BaseNode:
The BasicBlock could just contain a list of operations.
We will also need the successors/predecessors of basic blocks later for the spatial ir, but we could do that in a subclass of basic block.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +                if isinstance(value, list):
I am thinking if it's worth it to have a generic class NodeSequence[T] that provides a slightly more safe and extensible way to represent lists of nodes. It could have a builtin validate that ensures that all its elements conform to T. I could imagine that if we need to add more functionality on handling lists of nodes, this could be helpful.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +            if isinstance(old_value, list):
what about tuples?

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +                        elif not isinstance(value, BaseNode):
So this assumes that it returns a list or tuple or other sequence if it does not return a BaseNode?
I would at least add some assertion to that regard to clarify the intent. looks brittle.
Maybe the above idea for using a predefined NodeSequence interface/class could help, so we could actually match against that instead of doing a deduction by exclusion.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +        self.replace_count = 0
what is the use of replace_count? It is not really exposed as part of the interface of the class. either declare "nicely" + document or remove.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/language.lark
> +extent_interval_tuple : "[" dim ":" dim ("," dim ":" dim)* "]"
I would suggest to unify this with interval type.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/language.lark
> +extent_interval_tuple : "[" dim ":" dim ("," dim ":" dim)* "]"
also shouldnt it allow dim_or_end?

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/language.lark
> +interval_type : ("spst.")? "interval" "<" dim_or_end "," dim_or_end ">"
```
interval_tuple_short: dim_or_end ":" dim_or_end
interval_type : ("spst.")? "interval" "<" dim_or_end "," dim_or_end ">" | interval_tuple_short
```

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/language.lark
> +extent_type : ("spst.")? "extent" "<" extent_tuple_list ">"
```
extent_type_short : "{" extent_tuple_list "}"
extent_type: ("spst.")? "extent" "<" extent_tuple_list ">" | extent_type_short
```

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/language.lark
> +domain_type : ("spst.")? ("domain" | "cartesian") "<" dim_list ">"
domain_type_short : "["dim_list "]"
domain_type: ("spst.")? ("domain" | "cartesian") "<" dim_list ">" | domain_type_short

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +class TypeInfo(Node):
Maybe better named as 'OperationType'

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    typeinfo: TypeInfo
Maybe rename typeinfo to 'operation_type'

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    attributes: list[tuple[str, Node]]
todo: double check how this behaves with the visitors, what is the desired behavior when visiting attributes?

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    else_ifs: list[tuple[Identifier, list[StatementBlock | ReturnOp]]] | None  # List of (condition, body)
here, we definitely want to recurse into the elements of the else_ifs in the visitors, and they are tuples.

2024-08-13 14:58 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    interval: tuple[Interval, Interval, Interval]
here, I also think we would want to recurse into the interval when visiting, so tuples should be handled accordingly.

2024-08-13 15:01 UTC, luxfg commented on irspec/docs/stencil/stencil.md
> +    For example, `spst.cartesian<1, ?, 3>` is equivalent to `spst.cartesian<1, ?, 3>`
I fixed it.

2024-08-13 15:02 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    else_ifs: list[tuple[Identifier, list[StatementBlock | ReturnOp]]] | None  # List of (condition, body)
agreed, should work now.

2024-08-13 15:03 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    interval: tuple[Interval, Interval, Interval]
should work now, thanks!

2024-08-13 15:06 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/language.lark
> +extent_interval_tuple : "[" dim ":" dim ("," dim ":" dim)* "]"
> also shouldnt it allow dim_or_end?

Fixed.

2024-08-13 15:11 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    attributes: list[tuple[str, Node]]
should work now, though we could add `Attribute` as an explicit class if you wish to visit a specific attribute and access its name, e.g., when writing a node visitor.

2024-08-13 15:11 UTC, tbennun commented on spatialstencil/syntax/helpers.py
> +                if isinstance(value, list):
Fixed.

2024-08-13 15:12 UTC, tbennun commented on spatialstencil/syntax/helpers.py
> +            if isinstance(old_value, list):
Fixed.

2024-08-13 15:12 UTC, tbennun commented on spatialstencil/syntax/helpers.py
> +                        elif not isinstance(value, BaseNode):
Fixed

2024-08-13 15:13 UTC, tbennun commented on spatialstencil/syntax/helpers.py
> +        self.replace_count = 0
It is used to make sure something was replaced in some passes (field versioning I think?). I can document but cannot remove without adding another O(n) pass on the statements with yet a second visitor.

2024-08-13 15:14 UTC, tbennun commented on spatialstencil/syntax/helpers.py
> +class BaseNode:
I would call it Block rather than basic block (which would be used for a lower-level LLVM IR BB).

2024-08-13 15:15 UTC, tbennun commented on spatialstencil/syntax/helpers.py
> +Provides basic AST/IR utilities for traversal, transformation, and find/replacement.
Maybe node.py? Some nodes are AST nodes.

2024-08-13 15:15 UTC, tbennun commented on spatialstencil/syntax/helpers.py
> +def walk(node: BaseNode):
I copied the interface in Python's `ast` module. We can make it a method.

2024-08-13 16:04 UTC, luxfg requested changes
I reviewed the type inference. There is an inconsistency in the understanding of extent type inference.

2024-08-13 16:04 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/type_inference.py
> +    def _sort_extents(self, extent_set: dict[tuple[int | None], set[tuple[int | None]]]):
I am generally wondering about canonicalization. Should nodes have a method to canonicalize themselves? or should they be able to check if they are in canonical form?

2024-08-13 16:04 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/type_inference.py
> +class ExtentAssigner(sast.NodeTransformer):
(Ok, I see now that we get some boilerplate code for ensuring the types are updated everywhere, I think it's a reasonable solution using the Assigners.)

2024-08-13 16:04 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/analysis.py
> +    def flat_interval(self) -> tuple[int | None]:
Expected type 'tuple[int | None]', got 'tuple[int | Literal["?"] | None, ...]' instead

2024-08-13 16:04 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/analysis.py
> +        self.extents: dict[str, dict[tuple[int | None], set[tuple[int | None]]]] = defaultdict(lambda: defaultdict(set))
the types of self.extents are not correct here, I think the tuples should be different. A 3 tuple has type tuple[int | None, int | None, int | None]

2024-08-13 16:04 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/analysis.py
> +class ExtentCollector(sast.NodeVisitor):
The type checking is not consistent with the specification:

> The expression may only contain accesses to the fields `in_1, ... in _n` at the allowed extents.
> For any field, only accesses that are within their extent type are permitted within the statements.
> Which accesses are permitted is relative to the output's extent type.
> Specifically, every access to `(i, j, k)` is added to every output extent `(x, y, z)`
> and results in an access to `(i+x, j+y, k+z)`.
> 
> This corresponds to a Minkovski sum of the accesses of the statements and the accesses of the output's extent type._
> The arguments to the statement must be a sub-type of the union of all these accesses.
> Specifically, accessing a field with placeholders in their extent type always type checks.
> 


Specifically, if the output extent uses a non-zero offset access of %x, then this means we need to compute %x for additional extents.

2024-08-13 16:04 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/analysis.py
> +        return self.visit(node.value)
assert the type that node.value must have

2024-08-14 09:55 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/analysis.py
> +class ExtentCollector(sast.NodeVisitor):
I added some tests for the extent inference below to showcase the difference

2024-08-14 11:07 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +        self.replace_count = 0
ok, in that case add doc

2024-08-14 11:35 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +class BaseNode:
Block is good.

2024-08-14 11:35 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +class BaseNode:
Alternatively, if we have a generic NodeList class, we could just use that and I would be fine with it. So for example NodeList[AssignOp | ReturnOp]

2024-08-14 11:39 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    attributes: list[tuple[str, Node]]
ok. right now, it visits the nested nodes, but not the attributes themselves. This is fine I guess. Alternatively, we could also mandate the use of special NodeList and NodeTuple classes for nested nodes to make it more explicit what is visited and what is not. Right now, every Node nested somewhere within lists and tuples is visited.

2024-08-14 11:43 UTC, luxfg commented on spatialstencil/syntax/gt4py/astnodes.py
> +    def pretty(self, indent: int = 0) -> str:
printing should be in base node.

2024-08-14 11:51 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +class ASTFindReplace(ast.NodeTransformer):
I think ASTFindReplace should be in its own file, as it does not belong to the BaseNode and it could be confused to think it is a IRNodeTransformer when it is not.

2024-08-14 11:53 UTC, luxfg commented on spatialstencil/syntax/helpers.py
> +Provides basic AST/IR utilities for traversal, transformation, and find/replacement.
Ok, but the classes are called IRNodeVisitor, IRNodeTransformer. We can also split it up further, having a basenode.py and one or more *visitor(s).py

2024-08-16 09:28 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/type_inference.py
> +    def _sort_extents(self, extent_set: dict[tuple[int | None], set[tuple[int | None]]]):
you can also see this issue in two of the new tests (test_infer_extent_no_materialize / test_infer_extent_materialize). I think we would want to be able to get a canonical representation so that we can ensure that the as_ir strings always match for programs that only differ in the order of sets.

2024-08-16 09:33 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/analysis.py
> +class ExtentCollector(sast.NodeVisitor):
My rationale for this choice of definition is that we want to know which offsets are actually accessed, not just the values that appear in the syntax, which should make translation easier. I think it only shows up with no materialize for statements. In my view we do want to propagate the minkovski sum to the program arguments, so that means the program argument types are not necessarily equal to the types used by the statements, but are subtypes (see the example with materialize).

2024-08-16 10:37 UTC, luxfg commented on spatialstencil/syntax/stencil_ir/analysis.py
> +class ExtentCollector(sast.NodeVisitor):
Note that we will also need a pass that removes the non-materialized fields, so this could be a way around having to implement the extent inference for such fields (as we generally remove them before lowering). This pass will need a similar logic though as the type inference.

2024-08-17 18:32 UTC, tbennun commented on irspec/docs/stencil/stencil.md
> +  * For the purposes of type promotion, `bool` is considered a signed integral 1-bit value.
Fixed.

2024-08-17 18:38 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +class Domain(Node):
yes, done. and you can use the built-in Python `issubclass` or `isinstance`.

2024-08-17 18:42 UTC, tbennun commented on spatialstencil/syntax/helpers.py
> +class BaseNode:
Type is a reserved name in Python so I used `IRType`. We discussed NodeList so it stays list. Otherwise done.

2024-08-17 19:33 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +    attributes: list[tuple[str, Node]]
Fixed.

2024-08-17 19:34 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/irnodes.py
> +class TypeInfo(Node):
Fixed.

2024-08-17 19:35 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/analysis.py
> +        self.extents: dict[str, dict[tuple[int | None], set[tuple[int | None]]]] = defaultdict(lambda: defaultdict(set))
If you specify a tuple with one type, it is a variable-length tuple of that type (as far as I'm aware)

2024-08-18 23:29 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/analysis.py
> +        return self.visit(node.value)
The recursive visit ensures we get the right type of result. I don't understand what needs to be done here.

2024-08-18 23:44 UTC, tbennun commented on spatialstencil/syntax/stencil_ir/type_inference.py
> +    def _sort_extents(self, extent_set: dict[tuple[int | None], set[tuple[int | None]]]):
Canonicalization is implemented, the tests still fail (probably due to local extents as discussed in another comment). However, this note is resolved.

2024-08-19 10:40 UTC, luxfg approved these changes
We can merge the PR. Note that the type inference is still not as intended when no materialize is present and the extent types of computations are also not taking into account the dependencies between statements. I think we can fix it later though as well and I want to figure out what we actually need for lowering exactly.

2024-08-19 11:30 UTC, merged